version: '3.9'
services:

  web-server:
    image: nginx
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/data:/usr/share/nginx/html
#      - ./nginx/logs:/var/log/nginx
#      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
#      - application
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16.1
    container_name: pgsql-chatgateway
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    restart: unless-stopped


#  application:
#    image: java-db_kwork-image
#    container_name: java-db_kwork
#    build: .
#    env_file:
#      - postgres.env
#      - jwt.env
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - postgres
#      - minio

networks:
  default:
    driver: bridge
    name: docker-free
