server:
  port: 8081
  tomcat:
    reject-illegal-header: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import: optional:file:dev.env[.properties]

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA1}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  #
  #  sql:
  #    init:
  #      mode: always
  #      continue-on-error: false

  jpa:
    hibernate:
      ddl-auto: update #  update create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        default_schema: public
    defer-datasource-initialization: true

jwt:
  access-token-key: ${JWT_ACCESS_KEY}
  refresh-token-key: ${JWT_REFRESH_KEY}